name: CI

on:
  pull_request:
  push:
    branches:
      - '**'
    tags-ignore: # Do not run for tags
      - '**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test_linux_arm:
    strategy:
      matrix:
        node: [ 18 ]
    runs-on: ubuntu-latest
    name: Linux / Node ${{ matrix.node }} arm64
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Bewilderingly, `hashFiles('**/package.json')` is generating a different
      # hash in each caching step of this job. So that thing can take a hike.
      - run: echo -e "CACHE_KEY=$(shasum -a 256 package.json | cut -f1 -d ' ')" >> "$GITHUB_ENV"
      - name: Restore modules cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ github.workspace }}/node_modules
          key: linux-arm-node-${{ matrix.node }}-${{ env.CACHE_KEY }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: .
          build-args: |
            NODE_VERSION=${{ matrix.node }}
          file: linux_arm.dockerfile
          tags: linux_arm:node-${{ matrix.node }}
          load: true
          push: false
          platforms: linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Run test
        uses: addnab/docker-run-action@v3
        with:
          image: linux_arm:node-${{ matrix.node }}
          options: --platform linux/arm64 -v ${{ github.workspace }}:/host
          run: |
            cp -R /host/node_modules . 2>/dev/null
            rm -rf /host/node_modules 2>/dev/null
            npm install --verbose
            cp -R node_modules /host/
            npm run test
      - name: Update modules cache
        uses: actions/cache/save@v4
        # We always want to run this step even if the "test" step failed.
        if: '!cancelled()'
        with:
          path: ${{ github.workspace }}/node_modules
          key: linux-arm-node-${{ matrix.node }}-${{ env.CACHE_KEY }}
